# Generated by Django 4.2.6 on 2023-12-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_review_user"),
        ("profiles", "0002_alter_extendeduser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="visited",
            field=models.ManyToManyField(
                related_name="extended_visited", to="app.winery"
            ),
        ),
        migrations.AlterField(
            model_name="extendeduser",
            name="favorites",
            field=models.ManyToManyField(
                related_name="extended_favorites", to="app.winery"
            ),
        ),
    ]
