version: '3.8'

services:
  back-end:
    container_name: vino-back-end
    image: nikolapetrusev/dians-backend:0.2.1
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    container_name: vino-database
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.prod.db
  
  front-end:
    container_name: vino-front-end
    image: nikolapetrusev/dians-frontend:0.2.2
    ports:
      - 8080:8080
    depends_on:
      - back-end

volumes:
  postgres_data:
